# Generated by Django 5.1.1 on 2024-10-13 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_remove_profile_profile_picture_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
