# Generated by Django 5.1.1 on 2024-10-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
