# Generated by Django 5.0.6 on 2024-10-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sex',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='Unknown address', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Unknown Name', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_images/'),
        ),
    ]
